name: Run_Adblock_Reject_JSON  # 工作流名称

on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 版本作为运行环境

    steps:
    - name: Setup Node.js 20  # 设置 Node.js 20 环境
      uses: actions/setup-node@v3  # 使用官方的 setup-node 操作来设置 Node.js 环境
      with:
        node-version: '20'  # 指定使用 Node.js 版本 20

    - name: Checkout repository  # 检出代码仓库
      uses: actions/checkout@v3  # 使用官方的 checkout 操作来检出代码

    - name: Install PowerShell 7  # 安装 PowerShell 7
      run: |
        sudo apt-get update  # 更新包列表
        sudo apt-get install -y wget apt-transport-https software-properties-common  # 安装必要的包
        wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb  # 下载微软的包配置文件
        sudo dpkg -i packages-microsoft-prod.deb  # 安装包配置文件
        wget -q https://github.com/SagerNet/sing-box/releases/download/v1.11.15/sing-box_1.11.15_linux_amd64.deb  # 下载微软的包配置文件
        sudo dpkg -i sing-box_1.11.15_linux_amd64.deb  # 安装包配置文件
        sudo apt-get update  # 更新包列表
        sudo apt-get install -y powershell  # 安装 PowerShell 7
        rm packages-microsoft-prod.deb  # 删除包配置文件

    - name: Run adblock_rule_generator_json2.ps1   # 运行 adblock_rule_generator_json.ps1 脚本
      run: pwsh -File ./adblock_rule_generator_json2.ps1  # 使用 PowerShell 7 运行脚本



      # 步骤3：转换规则集（依赖于 sing-box.exe）
    - name: Release
      run: bash .github/release-rule-set.sh
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
